### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by kur1k0** [m5stack/uiflow-micropython#33]
I'm using ESP-IDF 5.0 and Python 3.13

```
kurikos-MacBook-Pro :: esp/uiflow_micropython/m5stack ‹master*› % make flash_all

Traceback (most recent call last):
  File "/Users/kuriko/esp/uiflow_micropython/m5stack/./../tools/nvs_partition_gen.py", line 38, in <module>
    from future.moves.itertools import zip_longest
  File "/Users/kuriko/.espressif/python_env/idf5.0_py3.13_env/lib/python3.13/site-packages/future/moves/__init__.py", line 5, in <module>
    from future.standard_library import import_top_level_modules
  File "/Users/kuriko/.espressif/python_env/idf5.0_py3.13_env/lib/python3.13/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
make: *** [nvs] Error 1

```
I don't know if this is a compatible problem between versions of ESP-IDF and Python or something. But the error disappeared when I changed "import imp" into "import importlib".

**Comment by Tinyu-Zhao** [comment]
python removed imp after 3.12

**Comment by bh1rio** [comment]
build it  with docker
