### ISSUE TITLE
M5 CAN module : OSError: (-261, 'ESP_ERR_NOT_FOUND')

### ISSUE THREAD

**Issue by mazcoder** [m5stack/uiflow-micropython#38]
Hello,

Trying to bring a CAN BUS module into UIFLOW2 with little success. I am micropython rookie.

As a first pass, I am simply trying to included example.

[dial_can_rx_example.m5f2](https://uiflow2.m5stack.com/?example=https://raw.githubusercontent.com/m5stack/uiflow-micropython/develop/examples/unit/can/dial_can_rx_example.m5f2)

But I receive the following error

`Traceback (most recent call last):
  File "<stdin>", line 40, in <module>
  File "<stdin>", line 28, in setup
  File "unit/can.py", line 1, in __init__
OSError: (-261, 'ESP_ERR_NOT_FOUND')`

I am not wise enough to know how to handle this. Can you help please?

**Comment by felmue** [comment]
Hello @mazcoder 

hmm, that receive (rx) example runs fine on my M5Dial.

- what kind of M5 device are you using?
- what are you using to send (tx) a CAN message?

Thanks
Felix
